### ISSUE TITLE
ES: Val d'Aran

### ISSUE THREAD

**Issue by fridlmue** [fridlmue/harbour-avarisk#18]
ES Val d'Aran: Source: https://conselharan2.cyberneticos.net/albina_files_local/latest/ (Probably this is a "test"-Location for those files at the moment)

Region: 
– Aran norte y centro
– Aran límite sur
– Aran vertiente sur

Region ID: 
ES-CT-L-01
ES-CT-L-02
ES-CT-L-03

Assignment not clear at the moment.

https://lauegi.conselharan.org/

**Comment by fridlmue** [comment]
Region is implemented, but RegionID to Region Name assignment is still not clear.

**Comment by simon04** [comment]
This file assigns IDs to region names to polygons: https://gitlab.com/albina-euregio/albina-admin-gui/-/blob/master/src/app/regions/regions.aran.geojson.json

**Comment by fridlmue** [comment]
@simon04 Thanks a lot for pointing me there! Very helpful!
